name: Update Ngrok URL

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual trigger
  push:
    branches: [ main ]    # Runs on each push to main

jobs:
  update-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Get Ngrok URL and update page
        env:
          NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
        run: node index.js
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add docs/index.html
          git commit -m "Update redirect URL" || exit 0
          git push
